# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20180424_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='dscription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='task',
            name='performers',
            field=models.ManyToManyField(related_name='_task_performers_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
