# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20180424_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='performers',
            field=models.ManyToManyField(related_name='performers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
